// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataPreprocessing.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250901022238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PreprocessingScriptStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ScriptContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("script_content");

                    b.HasKey("Id")
                        .HasName("pk_preprocessing_script_stores");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_preprocessing_script_stores_name");

                    b.ToTable("preprocessing_script_stores", (string)null);
                });

            modelBuilder.Entity("ProcessData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<int>("PreprocessingScriptStoreId")
                        .HasColumnType("integer")
                        .HasColumnName("preprocessing_script_store_id");

                    b.Property<int>("StatusProcess")
                        .HasColumnType("integer")
                        .HasColumnName("status_process");

                    b.HasKey("Id")
                        .HasName("pk_process_datas");

                    b.HasIndex("PreprocessingScriptStoreId")
                        .HasDatabaseName("ix_process_datas_preprocessing_script_store_id");

                    b.ToTable("process_datas", (string)null);
                });

            modelBuilder.Entity("ProcessData", b =>
                {
                    b.HasOne("PreprocessingScriptStore", "PreprocessingScriptStore")
                        .WithMany("ProcessDatas")
                        .HasForeignKey("PreprocessingScriptStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_process_datas_preprocessing_script_stores_preprocessing_scr");

                    b.Navigation("PreprocessingScriptStore");
                });

            modelBuilder.Entity("PreprocessingScriptStore", b =>
                {
                    b.Navigation("ProcessDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
